import os
from dotenv import load_dotenv

load_dotenv()

DRUM_INSTRUMENTS = ["snare", "crash", "floor_tom", "hi-hat", "kick", "rack_tom", "ride"]

INSTRUMENTS_DATA_SET_PATH = os.getenv("TRAINING_PATH")
VAL_SET_PATH = os.getenv("VAL_SET_PATH")
CUTTED_VAL_SETS_PATH = os.getenv("CUTTED_VAL_SETS_PATH")
TEST_TRACKS_PATH = os.getenv("TEST_TRACKS_PATH")
TO_CONVERT_PATH = os.getenv("TO_CONVERT_PATH")

CONVERTED_PATH = os.getenv("CONVERTED_PATH")
TRAINED_DL_MODELS_PATH = os.getenv("TRAINED_DL_MODELS_PATH")
TRAINED_ML_MODELS_PATH = os.getenv("TRAINED_ML_MODELS_PATH")
VISUALIZATIONS_AND_METRICS_BASE_PATH = os.getenv("VISUALTIZATIONS_AND_METRICS_PATH")
TRIAL_ARTIFACTS_PATH = os.getenv("TRIAL_ARTIFACTS_PATH")

TESTING_ONSETS_PATH = os.getenv("TESTING_ONSETS_PATH")

EVALUATION_RESULTS_PATH = os.getenv("EVALUATION_RESULTS_PATH")

MEL_BEST_CNN_MODEL_NAME = os.getenv("MEL_BEST_CNN_MODEL_NAME")
CQT_BEST_CNN_MODEL_NAME = os.getenv("CQT_BEST_CNN_MODEL_NAME")
MEL_CNN_MODEL_NAME = os.getenv("MEL_CNN_MODEL_NAME")
CQT_CNN_MODEL_NAME = os.getenv("CQT_CNN_MODEL_NAME")

MEL_BEST_LSTM_MODEL_NAME = os.getenv("MEL_BEST_LSTM_MODEL_NAME")
CQT_BEST_LSTM_MODEL_NAME = os.getenv("CQT_BEST_LSTM_MODEL_NAME")
MEL_LSTM_MODEL_NAME = os.getenv("MEL_LSTM_MODEL_NAME")
CQT_LSTM_MODEL_NAME = os.getenv("CQT_LSTM_MODEL_NAME")

MEL_BEST_CNN_LSTM_MODEL_NAME = os.getenv("MEL_BEST_CNN_LSTM_MODEL_NAME")
CQT_BEST_CNN_LSTM_MODEL_NAME = os.getenv("CQT_BEST_CNN_LSTM_MODEL_NAME")
MEL_CNN_LSTM_MODEL_NAME = os.getenv("MEL_CNN_LSTM_MODEL_NAME")
CQT_CNN_LSTM_MODEL_NAME = os.getenv("CQT_CNN_LSTM_MODEL_NAME")

MEL_BEST_TRANSFORMER_MODEL_NAME = os.getenv("MEL_BEST_TRANSFORMER_MODEL_NAME")
CQT_BEST_TRANSFORMER_MODEL_NAME = os.getenv("CQT_BEST_TRANSFORMER_MODEL_NAME")
MEL_TRANSFORMER_MODEL_NAME = os.getenv("MEL_TRANSFORMER_MODEL_NAME")
CQT_TRANSFORMER_MODEL_NAME = os.getenv("CQT_TRANSFORMER_MODEL_NAME")

DECISION_TREE_MODEL_NAME = os.getenv("DECISION_TREE_MODEL_NAME")
KNN_MODEL_NAME = os.getenv("KNN_MODEL_NAME")
LOGISTIC_REGRESSION_MODEL_NAME = os.getenv("LOGISTIC_REGRESSION_MODEL_NAME")
NAIVE_BAYES_MODEL_NAME = os.getenv("NAIVE_BAYES_MODEL_NAME")
STACKING_ENSEMBLE_MODEL_NAME = os.getenv("STACKING_ENSEMBLE_MODEL_NAME")
SVM_MODEL_NAME = os.getenv("SVM_MODEL_NAME")
TUNED_RANDOM_FOREST_MODEL_NAME = os.getenv("TUNED_RANDOM_FOREST_MODEL_NAME")
TUNED_SVM_MODEL_NAME = os.getenv("TUNED_SVM_MODEL_NAME")
VOTING_ENSEMBLE_MODEL_NAME = os.getenv("VOTING_ENSEMBLE_MODEL_NAME")

ENCODER_NAME = os.getenv("ENCODER_NAME")
SCALER_NAME = os.getenv("SCALER_NAME")

BATCH_SIZE = os.getenv("BATCH_SIZE")
NUM_WORKERS = os.getenv("NUM_WORKERS")
EPOCHS = os.getenv("EPOCHS")
PATIENCE = os.getenv("PATIENCE")
AUGUMENT_FACTOR = os.getenv("AUGUMENT_FACTOR")

CNN_LEARNING_RATE = os.getenv("CNN_LEARNING_RATE")
CNN_DROPOUT_RATE = os.getenv("CNN_DROPOUT_RATE")
CNN_WEIGHT_DECAY = os.getenv("CNN_WEIGHT_DECAY")
CNN_LABEL_SMOOTHING = os.getenv("CNN_LABEL_SMOOTHING")
CNN_SCHEDULER_ITERATIONS_NUM = 10
CNN_MINIMUM_LEARNING_RATE = 1e-6


GROOVE_MIDI_DATASET_PATH = "toImplement"
